{% set name = "caped-ai-augmentations" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caped-ai-augmentations-{{ version }}.tar.gz
  sha256: 1c88a9ff5ba9b8dccf150ccd321d9d188e4d8535e7afc90545943a46e8cb00cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - albumentations
    - dask-core
    - natsort
    - opencv
    - pandas
    - photutils
    - python >=3.9
    - scikit-learn
    - scipy

test:
  imports:
    - caped_ai_augmentations
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/caped-ai-augmentations/
  summary: |
    Augmentations for volume, planar segmentation, classification image
    segmentation and associated csv file of oneat clicks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
